#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. wmake/scripts/AllwmakeParseArguments

# Perform various checks
wmakeCheckPwd "$SIMULI_PROJECT_DIR" || {
    echo "Allwmake error: Current directory is not \$SIMULI_PROJECT_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the Simuli entries in your dot-files and source them."
    exit 1
}

[ -n "$SIMULI_EXT_LIBBIN" ] || {
    echo "Allwmake error: SIMULI_EXT_LIBBIN not set"
    echo "    Check the Simuli entries in your dot-files and source them."
    exit 1
}

# Compile wmake support applications
(cd wmake/src && make)

# Compile ThirdParty libraries and applications
if [ -d "$SIMULI_THIRD_PARTY_DIR" ]
then
    $SIMULI_THIRD_PARTY_DIR/Allwmake
else
    echo "Allwmake: no ThirdParty directory found - skipping"
fi

# Compile Simuli libraries and applications
src/Allwmake $targetType $*

# Compile Simuli applications
applications/Allwmake $targetType $*
