#                            -*- mode: org; -*-
#
#+TITLE:     README for [[http://simuli.org][Simuli]]
#+AUTHOR:               The Simuli Team
#+DATE:                     16th August 2025
#+LINK:                  http://simuli.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2025 Simuli Team.

* About Simuli
  Simuli is a free, open-source computational fluid dynamics (CFD) and engineering
  simulation platform. It is designed for engineers, researchers, and students who
  need a flexible and powerful tool to simulate complex systems. Simuli can handle
  fluid flows, turbulence, heat transfer, chemical reactions, solid mechanics, and
  electromagnetics, making it suitable for both academic and industrial applications.

* License
  Simuli is free software: you can redistribute it and/or modify it under the terms
  of the GNU General Public License as published by the Free Software Foundation,
  either version 3 of the License, or (at your option) any later version.
  See the file =COPYING= in this directory or [[http://www.gnu.org/licenses/]]
  for a description of the GNU General Public License terms.

* [[https://simuli.org/download/source][Download and installation instructions]]
* [[https://simuli.org/resources][Documentation]]
* [[https://simuli.org/source-docs][Source code documentation]]
* [[https://simuli.org/dev/coding-style-guide][Simuli C++ Style Guide]]
* [[https://simuli.org/bugs][Reporting bugs in Simuli]]
* [[https://simuli.org/contact][Contacting the Simuli Team]]
